name: Scala CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK 11 with the correct distribution
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Use 'temurin' for JDK

      # Install sbt using SDKMAN (a more reliable option)
      - name: Install sbt using SDKMAN
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install sbt

      # Resolve sbt dependencies (this downloads the dependencies listed in your build.sbt)
      - name: Resolve sbt dependencies
        run: sbt update

      # Build the project
      - name: Build project
        run: sbt clean compile

      # Run the Scala application with the specified dataset paths
      - name: Run Scala application
        run: |
        #src/main/scala/org/example/DistributedComputingTasks.scala
          sbt "run  src/test/dataset_a/dataset_a.parquet src/test/dataset_b/dataset_b.parquet src/test/dataset_c/dataset_c.parquet 10" || exit 1

      # Optionally, upload the output (parquet file) as an artifact for debugging
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: parquet-output
          path: src/test/dataset_c/dataset_c.parquet  # Path to the output dataset
