name: Scala CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK 11 with the correct distribution
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Use 'temurin' for JDK

      # Install sbt (Scala build tool) from the official repository
      - name: Install sbt
        run: |
          echo "Installing sbt..."
          # Add the official sbt repository
          echo "deb https://repo.scala-sbt.org/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
          curl -sL https://keybase.io/sbt/bundle/sbt.asc | gpg --dearmor | sudo tee /usr/share/keyrings/sbt-archive-keyring.gpg > /dev/null
          sudo apt-get update
          sudo apt-get install sbt

      # Resolve sbt dependencies (this downloads the dependencies listed in your build.sbt)
      - name: Resolve sbt dependencies
        run: sbt update

      # Build the project
      - name: Build project
        run: sbt clean compile

      # Run the Scala application with the specified dataset paths
      - name: Run Scala application
        run: |
          sbt "run src/main/scala/org/example/DistributedComputingTasks.scala src/test/dataset_a/dataset_a.parquet src/test/dataset_b/dataset_b.parquet src/test/dataset_c/dataset_c.parquet 10" || exit 1

      # Optionally, upload the output (parquet file) as an artifact for debugging
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: parquet-output
          path: src/test/dataset_c/dataset_c.parquet  # Path to the output dataset
